version: '3.8'

services:
  fastapi-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      # Add any environment variables if needed
      # Example:
      # - ENV_VAR_NAME=value
    volumes:
      - .:/app